<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="16.1.1" />
    <PackageReference Include="LinqKit.Core" Version="1.2.11" />
    <PackageReference Include="MediatR" Version="14.1.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Domain\Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="CQRS\Offer\Queries\" />
    <Folder Include="CQRS\Reservation\Queries\" />
    <Folder Include="CQRS\RoomOffer\Queries\" />
    <Folder Include="CQRS\RoomPicture\Queries\" />
    <Folder Include="CQRS\ReservationRoom\Command\" />
  </ItemGroup>

</Project>
